version: '3.8'

services:
  db:
    image: postgres:16
    container_name: jellypado-postgres
    restart: always
    environment:
      POSTGRES_DB: jellypado
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 